#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${POSTGRES_NONROOT_USER} WITH PASSWORD '${POSTGRES_NONROOT_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOINHERIT;
	CREATE DATABASE app_database OWNER ${POSTGRES_NONROOT_USER} ENCODING 'UTF8';
EOSQL
