version: "3.8"
services:
  postgres:
    container_name: postgres
    expose:
      - 5432
    volumes:
      - postgres-rss-feed:/var/lib/postgresql/data/
    networks:
      - rss-feed-network
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true

  fetcher:
    container_name: rss-feed_fetcher
    image: ghcr.io/gordonpn/rss-feed_fetcher:stable
    networks:
      - rss-feed-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s

  backend:
    container_name: rss-feed_backend
    image: ghcr.io/gordonpn/rss-feed_backend:stable
    networks:
      - rss-feed-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s

volumes:
  postgres-rss-feed:
    external:
      name: postgres-rss-feed

networks:
  rss-feed-network:
    driver: overlay
  traefik-public:
    external: true
    driver: overlay
