version: "3.8"
services:
  postgres:
    container_name: postgres
    expose:
      - 5432
    volumes:
      - postgres-rss-feed:/var/lib/postgresql/data/
    networks:
      - rss-feed-network
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true

  fetcher:
    container_name: rss-feed_fetcher
    image: ghcr.io/gordonpn/rss-feed_fetcher:stable
    networks:
      - rss-feed-network
    volumes:
      - ${DATA_JSON}:/app/data.json
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true

  backend:
    container_name: rss-feed_backend
    image: ghcr.io/gordonpn/rss-feed_backend:stable
    networks:
      - rss-feed-network
    healthcheck:
      test: curl --fail -s http://localhost:8080/api/v1/healthcheck || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s

  proxy:
    container_name: rss-feed_proxy
    image: ghcr.io/gordonpn/rss-feed_proxy:stable
    networks:
      - traefik-public
      - rss-feed-network
    expose:
      - 80
    healthcheck:
      test: curl --fail -s http://localhost:80/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.rss-feed.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"

volumes:
  postgres-rss-feed:
    external:
      name: postgres-rss-feed

networks:
  rss-feed-network:
    driver: overlay
  traefik-public:
    external: true
    driver: overlay
