version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_NONROOT_PASSWORD
      - POSTGRES_NONROOT_USER
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - TZ=America/Montreal
    volumes:
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
