version: "3.8"
services:
  postgres:
    container_name: rss-feed_postgres-dev
    volumes:
      - dev-postgres-rss-feed:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"

  fetcher:
    container_name: rss-feed_fetcher-dev
    build:
      context: ./fetcher
      dockerfile: Dockerfile.dev
    volumes:
      - ./fetcher/data.json:/app/data.json
    environment:
      - DEV=true

  backend:
    container_name: rss-feed_backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DEV=true
      - POSTGRES_HOST=localhost
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  dev-postgres-rss-feed:
    external:
      name: dev-postgres-rss-feed
