version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_NONROOT_PASSWORD
      - POSTGRES_NONROOT_USER
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - TZ=America/Montreal
    volumes:
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  fetcher:
    build:
      context: ./fetcher
      dockerfile: Dockerfile
    environment:
      - FETCHER_HC_UUID
      - POSTGRES_NONROOT_PASSWORD
      - POSTGRES_NONROOT_USER
      - REDDIT_ID
      - REDDIT_PASSWORD
      - REDDIT_SECRET
      - REDDIT_USERNAME
      - TZ=America/Montreal
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_NONROOT_PASSWORD
      - POSTGRES_NONROOT_USER
      - TZ=America/Montreal
    restart: unless-stopped
    depends_on:
      - postgres
