name: build
on: push

jobs:
  build:
    strategy:
      matrix:
        go: ["1.14", "1.15"]
        project: [backend, fetcher]
        arch: ["amd64", "arm64"]

    runs-on: ubuntu-latest

    env:
      GOOS: linux
      GOARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Go project ${{ matrix.project }}
        run: |
          cd ./${{ matrix.project }}
          go build

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: failure()
